# Changes here will be overwritten by Copier
_commit: 1.0.8
_src_path: gh:pawamoy/copier-uv
author_email: dev@pawamoy.fr
author_fullname: Timothée Mazzucotelli
author_username: pawamoy
copyright_date: '2024'
copyright_holder: Timothée Mazzucotelli
copyright_holder_email: dev@pawamoy.fr
copyright_license: ISC License
insiders: true
insiders_email: insiders@pawamoy.fr
insiders_repository_name: griffe-typedoc
project_description: Signatures for entire TypeScript programs using TypeDoc.
project_name: Griffe TypeDoc
public_release: false
python_package_command_line_name: griffe-typedoc
python_package_distribution_name: griffe-typedoc
python_package_import_name: griffe_typedoc
repository_name: griffe-typedoc
repository_namespace: mkdocstrings
repository_provider: github.com

